# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: ["--config=backend/setup.cfg"]
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
        args: ["--config=backend/setup.cfg"]
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--resolve-all-configs"]
-   repo: local
    hooks:
    -   id: sync-reqs
        name: Sync requirements
        entry: bash -c "cd backend && make sync-reqs"
        language: system
        always_run: true
