export const LEGISLATORS_BY_PARTY: Record<string, string[]> = {
    "Somos Fueguinos": [
        "Ricardo Garramuño"
    ],
    "Unión Por La Patria": [
        "Roberto Mario Mirabella",
        "Pablo Ismael Outes",
        "Pamela Calletti",
        "Yolanda Graciela Vega",
        "Adolfo Bermejo",
        "Agustina Lucrecia Propato",
        "Aldo Adolfo Leiva",
        "Ana Carolina Gaillard",
        "Ana Fabiola Aubone",
        "Ana Maria Ianni",
        "Andrea Graciela Freites",
        "Ariel Rauschenberger",
        "Bernardo Jose \"Pepe\" Herrera",
        "Blanca Ines Osuna",
        "Brenda Magali Vargas Matyi",
        "Carlos Cisneros",
        "Carlos Salomon Heller",
        "Carolina Yutrovic",
        "Castagneto, Carlos",
        "Celia Maria Campitelli",
        "Christian Alejandro Zulli",
        "Constanza Maria Alonso",
        "Daniel Fernando Arroyo",
        "Daniel Gustavo Gollan",
        "Dante Edgardo Lopez Rodriguez",
        "David Sebastian Noblega",
        "Diego Giuliano",
        "Eduardo Felix Valdes",
        "Eduardo Leandro Toniolli",
        "Emiliano Estrada",
        "Ernesto Nader Ali",
        "Estela Mary Del Rosario Neder",
        "Gabriela Beatriz Estevez",
        "Gabriela Pedrali",
        "German Pedro Martinez",
        "Guillermo Snopek",
        "Gustavo Carlos Miguel Gonzalez",
        "Gustavo Eduardo Bordet",
        "Gustavo Ramiro Fernandez Patri",
        "Gutierrez, Carlos Ramiro",
        "Hilda Clelia Aguirre",
        "Hugo Ruben Yasky",
        "Itai Hagman",
        "Jorge Antonio Romero",
        "Jorge Eduardo Chica Muñoz",
        "Jorge Neri Araujo Hernandez",
        "Jorge Ricardo Herrera",
        "Jose Edgardo Gomez",
        "José Alejandro Glinski",
        "Juan Manuel Pedrini",
        "Julia Strada Rodriguez",
        "Julio Cesar Pereyra",
        "Kirchner, Maximo",
        "Leandro Jorge Santoro",
        "Leila Susana Chaher",
        "Leopoldo Raul Guido Moreau",
        "Lili Paponet",
        "Lorena Iris Pokoik Garcia",
        "Luciana Potenza",
        "Luis Eugenio Basterra",
        "Magali Mastaler",
        "Marcela Fabiana Passo",
        "Maria Eugenia Alianiello",
        "Maria Fernanda Avila",
        "Maria Florencia Carignano",
        "Maria Gisela Marziotta",
        "Maria Graciela Parola",
        "Maria Luisa Chomiak",
        "Maria Luisa Montoto De Rogel",
        "Marino, Juan",
        "Mario Roberto Manrique",
        "Martin Aveiro",
        "Martin Ignacio Soria",
        "Matias Molle",
        "Micaela Moran",
        "Monica Edith Litza",
        "Monica Fernanda Macha",
        "Moreau, Cecilia",
        "Nancy Sand",
        "Nilda Moyano",
        "Pablo Carro",
        "Pablo Todero",
        "Pablo Yedlin",
        "Paula Andrea Penacca",
        "Ricardo Daniel Daives",
        "Rogelio Iparraguirre",
        "Roxana Elizabeth Monzon",
        "Sabrina Selva",
        "Santiago A. Cafiero",
        "Sergio Guillermo Casas",
        "Sergio Omar Palazzo",
        "Silvana Micaela Ginocchio",
        "Tailhade, Rodolfo",
        "Tanya Bertoldi",
        "Tomas Ledesma",
        "Vanesa Raquel Siley",
        "Varinia Lichi Marin",
        "Victoria Tolosa Paz",
        "Volnovich, Luana",
        "Walberto E. Allende",
        "Zaracho, Natalia",
        "Agustin Fernandez",
        "Elia Mansilla",
        "Gladys Medina",
        "\"Colo\" Vancsik Daniel A.",
        "Arrua Pedro Alberto",
        "Carlos Alberto Fernandez",
        "Ruiz Yamila Lisette"
    ],
    "Juntos Somos Rio Negro": [
        "Agustin Domingo"
    ],
    "Movimiento Popular Neuquino": [
        "Osvaldo Llancafilo"
    ],
    "Somos Energia Para Renovar Santa Cruz - Ser": [
        "Carlos Facundo Prades",
        "Sergio Edgardo Acevedo"
    ],
    "Alianza Por Santa Cruz": [
        "Jose Luis Garrido"
    ],
    "Frente De Izquierda Y De Trabajadores-Unidad": [
        "Myriam Teresa Bregman",
        "Romina Del Pla",
        "Monica Leticia Schlotthauer",
        "Juan Carlos Giordano",
        "Mercedes De Mendieta",
        "Vilma Ripoll",
        "Vanina Natalia Biasi",
        "Alejandro Ariel Vilca",
        "Christian Carlos Hernan Castillo",
        "Nicolas Del Caño"
    ],
    "Alianza Fuerza San Luis": [
        "Maria Natalia Zabala Chacur"
    ],
    "La Libertad Avanza": [
        "Lourdes Micaela Arrieta",
        "Alberto “Bertie” Tiburcio Benegas Lynch",
        "Alida Monica Ferreyra",
        "Beltran Benedit",
        "Carla Juliana Santillan Juarez Brahim",
        "Carlos Alberto Gonzalez D Alessandro",
        "Carlos Daniel Garcia",
        "Carolina Rosana Piparo",
        "Cesar Hernan Treffinger",
        "Claudio Lisandro Almiron",
        "Facundo Correa Llano",
        "Gabriel Marcos Bornoroni",
        "Gerardo Gustavo Gonzalez",
        "Jose Asad Peluc",
        "José Luis Espert",
        "Julio Aurelio Moreno",
        "Lilia Adela Bolukalo Lemoine",
        "Manuel Quintar",
        "Marcela Marina Pagano",
        "Maria Celeste Ponce",
        "Maria Emilia Orozco",
        "Maria Fernanda Araujo",
        "Maria Lorena Macyszyn",
        "Maria Lorena Villaverde",
        "Maria Mercedes Llano",
        "Mario Gerardo Huesen",
        "Martin Alexis Menem",
        "Nadia Judith Marquez",
        "Nicolas Fernando Mayoraz",
        "Nicolas Mario Emma",
        "Pablo Miguel Ansaloni",
        "Rocio Belen Bonacci",
        "Romina Diez",
        "Santiago Javier Santurio Rodriguez",
        "Eduardo Gabriel Falcone",
        "Maria Cecilia Ibañez",
        "Oscar Roberto Zago"
    ],
    "Juntos Por El Cambio": [
        "Alberto Gustavo Arancibia Rodriguez",
        "Alvaro Martinez",
        "Carlos Raúl Zapata",
        "Florencia Klipauka Lewtak",
        "Guillermo Tristan Montenegro",
        "Maria De Los Angeles Moreno",
        "Nancy Viviana Picon Martinez",
        "Juan Manuel Lopez",
        "Maria Marcela Campagnoli",
        "Maria Victoria Borrego",
        "Maximiliano Carlos Francisco Ferraro",
        "Monica Edith Frade",
        "Paula Mariana Oliveto Lago",
        "Paula Omodeo",
        "Carla Carrizo",
        "Danya Tavela",
        "Facundo Manes",
        "Fernando Carbajal",
        "Jorge Colo Rizzotti",
        "Juan Carlos Polini",
        "Manuel \"Colo\" Aguirre",
        "Marcela Antola",
        "Marcela Coli",
        "Mariela Giselle Coletta",
        "Melina C. Giorgi",
        "Pablo Adrian Juliano",
        "Emilio Monzó",
        "Francisco Alejandro Morchio",
        "Jorge Antonio Avila",
        "Margarita Rosa Stolbizer",
        "Miguel Angel Pichetto",
        "Nicolás María Massot",
        "Oscar Agost Carreño",
        "Ricardo Hipolito Lopez Murphy",
        "Alejandro Bongiovanni",
        "Alejandro Oscar Finocchiaro",
        "Alvaro Gustavo Gonzalez",
        "Ana Clara Romero",
        "Anibal Tortoriello",
        "Cristian Adrian Ritondo",
        "Daiana Fernandez Molero",
        "Damian Eduardo Arabia",
        "Diego Cesar Santilli",
        "Fernando Adolfo Iglesias",
        "Gabriel Chumpitaz",
        "Gabriela Gisel Besana",
        "Gerardo Fabian Milman",
        "Germana Maria Figueroa Casas",
        "Hector \"La Coneja\" Baldassi",
        "Hernan Santiago Lombardi",
        "Javier Sanchez Wrba",
        "Jose Negro Nuñez",
        "Karina Bachey",
        "Laura Rodriguez Machado",
        "Luciano Laspina",
        "Maria Angel Sotolano",
        "Maria Belen Avico",
        "Maria Eugenia Vidal",
        "Maria Florencia De Sensi",
        "Marilu Quiroz",
        "Martin Ivan Yeza",
        "Martin Maquieyra",
        "Martin Miguel Ardohain",
        "Nancy Mariana Ballejos",
        "Patricia Maria Vasquez",
        "R. Emmanuel Bianchetti",
        "Sabrina Carlota Ajmechet",
        "Sergio Capozzi",
        "Silvana Myriam Giudici",
        "Silvia Gabriela Lospennato",
        "Sofia Brambilla",
        "Tito Stefani",
        "Veronica Gabriela Razzini",
        "Mario Domingo Barletta",
        "Alfredo Oscar Vallejos",
        "Atilio Francisco Salvador Benedetti",
        "Fabio Jose Quetglas",
        "Francisco Manuel Monti",
        "Gabriela Brouwer De Koning",
        "Gerardo Cipolini",
        "Jose Federico Tournier",
        "Julio Cobos",
        "Karina Veronica Banfi",
        "Lisandro Nieri",
        "Luis Albino Picat",
        "Mariano Campero",
        "Mario Pablo Cervi",
        "Martin A. Arjol",
        "Martin Alberto Tetaz",
        "Natalia Silvina Sarapura",
        "Pamela Verasay",
        "Pedro Galimberti",
        "Roberto Antonio Sanchez",
        "Rodrigo De Loredo",
        "Roxana Reyes",
        "Soledad Carrizo"
    ],
    "Republicanos Unidos": [
        "Jorge Santiago Pauli"
    ],
    "Hacemos Por Nuestro Pais": [
        "Alejandra Torres",
        "Carlos Mario Gutierrez",
        "Esteban Paulon",
        "Florencio Randazzo",
        "Ignacio José Garcia Aresca",
        "Juan Fernando Brügge",
        "Natalia De La Sota"
    ],
    "Frente Amplio Progresista": [
        "Monica Fein"
    ]
};