export const PARLIAMENTARY_BLOCS: string[] = [
    "Por Santa Cruz",
    "Encuentro Federal",
    "Union Por La Patria",
    "Democracia Para Siempre",
    "Pro",
    "La Libertad Avanza",
    "Ucr - Union Civica Radical",
    "Fuerzas Del Cielo - Espacio Liberal F.c.e",
    "Innovacion Federal",
    "Unidos",
    "Partido Obrero -frente De Izquierda Y De Trabajadores -unidad",
    "Coalicion Civica",
    "Pts-frente De Izquierda Unidad",
    "Mid - Movimiento De Integracion Y Desarrollo",
    "Independencia",
    "Movimiento Popular Neuquino",
    "Produccion Y Trabajo",
    "Creo",
    "Izquierda Socialista Fit-unidad",
    "Buenos Aires Libre",
    "Hacemos Coalicion Federal",
    "Partido Obrero-frente De Izquierda Y Trabajadores Unidad",
    "Frente De Izquierda Y De Trabajadores Unidad",
    "Avanza Libertad",
    "La Union Mendocina",
    "Liga Del Interior Eli",
    "Coherencia",
    "Futuro Y Libertad",
    "Somos Fueguinos",
    "Republicanos Unidos",
    "Defendamos Santa Fe",
    "Mst - Frente De Izquierda Y Trabajadores Unidad",
    "Transformacion",
    "Izquierda Socialista-fit-unidad",
    "Transformacion B.t",
    "Bloque Sin Definir"
]