export const PARTIES_BY_LEGISLATORS: Record<string, string> = {
    'Ricardo Garramuño': 'Somos Fueguinos',
    'Roberto Mario Mirabella': 'Unión Por La Patria',
    '"Colo" Vancsik Daniel A.': 'Unión Por La Patria',
    'Agustin Domingo': 'Juntos Somos Rio Negro',
    'Arrua Pedro Alberto': 'Unión Por La Patria',
    'Carlos Alberto Fernandez': 'Unión Por La Patria',
    'Pablo Ismael Outes': 'Unión Por La Patria',
    'Pamela Calletti': 'Unión Por La Patria',
    'Ruiz Yamila Lisette': 'Unión Por La Patria',
    'Yolanda Graciela Vega': 'Unión Por La Patria',
    'Osvaldo Llancafilo': 'Movimiento Popular Neuquino',
    'Carlos Facundo Prades': 'Somos Energia Para Renovar Santa Cruz - Ser',
    'Jose Luis Garrido': 'Alianza Por Santa Cruz',
    'Sergio Edgardo Acevedo': 'Somos Energia Para Renovar Santa Cruz - Ser',
    'Myriam Teresa Bregman': 'Frente De Izquierda Y De Trabajadores-Unidad',
    'Romina Del Pla': 'Frente De Izquierda Y De Trabajadores-Unidad',
    'Monica Leticia Schlotthauer': 'Frente De Izquierda Y De Trabajadores-Unidad',
    'Juan Carlos Giordano': 'Frente De Izquierda Y De Trabajadores-Unidad',
    'Mercedes De Mendieta': 'Frente De Izquierda Y De Trabajadores-Unidad',
    'Vilma Ripoll': 'Frente De Izquierda Y De Trabajadores-Unidad',
    'Vanina Natalia Biasi': 'Frente De Izquierda Y De Trabajadores-Unidad',
    'Alejandro Ariel Vilca': 'Frente De Izquierda Y De Trabajadores-Unidad',
    'Christian Carlos Hernan Castillo': 'Frente De Izquierda Y De Trabajadores-Unidad',
    'Nicolas Del Caño': 'Frente De Izquierda Y De Trabajadores-Unidad',
    'Adolfo Bermejo': 'Unión Por La Patria',
    'Agustina Lucrecia Propato': 'Unión Por La Patria',
    'Aldo Adolfo Leiva': 'Unión Por La Patria',
    'Ana Carolina Gaillard': 'Unión Por La Patria',
    'Ana Fabiola Aubone': 'Unión Por La Patria',
    'Ana Maria Ianni': 'Unión Por La Patria',
    'Andrea Graciela Freites': 'Unión Por La Patria',
    'Ariel Rauschenberger': 'Unión Por La Patria',
    'Bernardo Jose "Pepe" Herrera': 'Unión Por La Patria',
    'Blanca Ines Osuna': 'Unión Por La Patria',
    'Brenda Magali Vargas Matyi': 'Unión Por La Patria',
    'Carlos Cisneros': 'Unión Por La Patria',
    'Carlos Salomon Heller': 'Unión Por La Patria',
    'Carolina Yutrovic': 'Unión Por La Patria',
    'Castagneto, Carlos': 'Unión Por La Patria',
    'Celia Maria Campitelli': 'Unión Por La Patria',
    'Christian Alejandro Zulli': 'Unión Por La Patria',
    'Constanza Maria Alonso': 'Unión Por La Patria',
    'Daniel Fernando Arroyo': 'Unión Por La Patria',
    'Daniel Gustavo Gollan': 'Unión Por La Patria',
    'Dante Edgardo Lopez Rodriguez': 'Unión Por La Patria',
    'David Sebastian Noblega': 'Unión Por La Patria',
    'Diego Giuliano': 'Unión Por La Patria',
    'Eduardo Felix Valdes': 'Unión Por La Patria',
    'Eduardo Leandro Toniolli': 'Unión Por La Patria',
    'Emiliano Estrada': 'Unión Por La Patria',
    'Ernesto Nader Ali': 'Unión Por La Patria',
    'Estela Mary Del Rosario Neder': 'Unión Por La Patria',
    'Gabriela Beatriz Estevez': 'Unión Por La Patria',
    'Gabriela Pedrali': 'Unión Por La Patria',
    'German Pedro Martinez': 'Unión Por La Patria',
    'Guillermo Snopek': 'Unión Por La Patria',
    'Gustavo Carlos Miguel Gonzalez': 'Unión Por La Patria',
    'Gustavo Eduardo Bordet': 'Unión Por La Patria',
    'Gustavo Ramiro Fernandez Patri': 'Unión Por La Patria',
    'Gutierrez, Carlos Ramiro': 'Unión Por La Patria',
    'Hilda Clelia Aguirre': 'Unión Por La Patria',
    'Hugo Ruben Yasky': 'Unión Por La Patria',
    'Itai Hagman': 'Unión Por La Patria',
    'Jorge Antonio Romero': 'Unión Por La Patria',
    'Jorge Eduardo Chica Muñoz': 'Unión Por La Patria',
    'Jorge Neri Araujo Hernandez': 'Unión Por La Patria',
    'Jorge Ricardo Herrera': 'Unión Por La Patria',
    'Jose Edgardo Gomez': 'Unión Por La Patria',
    'José Alejandro Glinski': 'Unión Por La Patria',
    'Juan Manuel Pedrini': 'Unión Por La Patria',
    'Julia Strada Rodriguez': 'Unión Por La Patria',
    'Julio Cesar Pereyra': 'Unión Por La Patria',
    'Kirchner, Maximo': 'Unión Por La Patria',
    'Leandro Jorge Santoro': 'Unión Por La Patria',
    'Leila Susana Chaher': 'Unión Por La Patria',
    'Leopoldo Raul Guido Moreau': 'Unión Por La Patria',
    'Lili Paponet': 'Unión Por La Patria',
    'Lorena Iris Pokoik Garcia': 'Unión Por La Patria',
    'Luciana Potenza': 'Unión Por La Patria',
    'Luis Eugenio Basterra': 'Unión Por La Patria',
    'Magali Mastaler': 'Unión Por La Patria',
    'Marcela Fabiana Passo': 'Unión Por La Patria',
    'Maria Eugenia Alianiello': 'Unión Por La Patria',
    'Maria Fernanda Avila': 'Unión Por La Patria',
    'Maria Florencia Carignano': 'Unión Por La Patria',
    'Maria Gisela Marziotta': 'Unión Por La Patria',
    'Maria Graciela Parola': 'Unión Por La Patria',
    'Maria Luisa Chomiak': 'Unión Por La Patria',
    'Maria Luisa Montoto De Rogel': 'Unión Por La Patria',
    'Maria Natalia Zabala Chacur': 'Alianza Fuerza San Luis',
    'Marino, Juan': 'Unión Por La Patria',
    'Mario Roberto Manrique': 'Unión Por La Patria',
    'Martin Aveiro': 'Unión Por La Patria',
    'Martin Ignacio Soria': 'Unión Por La Patria',
    'Matias Molle': 'Unión Por La Patria',
    'Micaela Moran': 'Unión Por La Patria',
    'Monica Edith Litza': 'Unión Por La Patria',
    'Monica Fernanda Macha': 'Unión Por La Patria',
    'Moreau, Cecilia': 'Unión Por La Patria',
    'Nancy Sand': 'Unión Por La Patria',
    'Nilda Moyano': 'Unión Por La Patria',
    'Pablo Carro': 'Unión Por La Patria',
    'Pablo Todero': 'Unión Por La Patria',
    'Pablo Yedlin': 'Unión Por La Patria',
    'Paula Andrea Penacca': 'Unión Por La Patria',
    'Ricardo Daniel Daives': 'Unión Por La Patria',
    'Rogelio Iparraguirre': 'Unión Por La Patria',
    'Roxana Elizabeth Monzon': 'Unión Por La Patria',
    'Sabrina Selva': 'Unión Por La Patria',
    'Santiago A. Cafiero': 'Unión Por La Patria',
    'Sergio Guillermo Casas': 'Unión Por La Patria',
    'Sergio Omar Palazzo': 'Unión Por La Patria',
    'Silvana Micaela Ginocchio': 'Unión Por La Patria',
    'Tailhade, Rodolfo': 'Unión Por La Patria',
    'Tanya Bertoldi': 'Unión Por La Patria',
    'Tomas Ledesma': 'Unión Por La Patria',
    'Vanesa Raquel Siley': 'Unión Por La Patria',
    'Varinia Lichi Marin': 'Unión Por La Patria',
    'Victoria Tolosa Paz': 'Unión Por La Patria',
    'Volnovich, Luana': 'Unión Por La Patria',
    'Walberto E. Allende': 'Unión Por La Patria',
    'Zaracho, Natalia': 'Unión Por La Patria',
    'Lourdes Micaela Arrieta': 'La Libertad Avanza',
    'Agustin Fernandez': 'Unión Por La Patria',
    'Elia Mansilla': 'Unión Por La Patria',
    'Gladys Medina': 'Unión Por La Patria',
    'Alberto Gustavo Arancibia Rodriguez': 'Juntos Por El Cambio',
    'Alberto “Bertie” Tiburcio Benegas Lynch': 'La Libertad Avanza',
    'Alida Monica Ferreyra': 'La Libertad Avanza',
    'Alvaro Martinez': 'Juntos Por El Cambio',
    'Beltran Benedit': 'La Libertad Avanza',
    'Carla Juliana Santillan Juarez Brahim': 'La Libertad Avanza',
    'Carlos Alberto Gonzalez D Alessandro': 'La Libertad Avanza',
    'Carlos Daniel Garcia': 'La Libertad Avanza',
    'Carlos Raúl Zapata': 'Juntos Por El Cambio',
    'Carolina Rosana Piparo': 'La Libertad Avanza',
    'Cesar Hernan Treffinger': 'La Libertad Avanza',
    'Claudio Lisandro Almiron': 'La Libertad Avanza',
    'Facundo Correa Llano': 'La Libertad Avanza',
    'Florencia Klipauka Lewtak': 'Juntos Por El Cambio',
    'Gabriel Marcos Bornoroni': 'La Libertad Avanza',
    'Gerardo Gustavo Gonzalez': 'La Libertad Avanza',
    'Guillermo Tristan Montenegro': 'Juntos Por El Cambio',
    'Jorge Santiago Pauli': 'Republicanos Unidos',
    'Jose Asad Peluc': 'La Libertad Avanza',
    'José Luis Espert': 'La Libertad Avanza',
    'Julio Aurelio Moreno': 'La Libertad Avanza',
    'Lilia Adela Bolukalo Lemoine': 'La Libertad Avanza',
    'Manuel Quintar': 'La Libertad Avanza',
    'Marcela Marina Pagano': 'La Libertad Avanza',
    'Maria Celeste Ponce': 'La Libertad Avanza',
    'Maria Emilia Orozco': 'La Libertad Avanza',
    'Maria Fernanda Araujo': 'La Libertad Avanza',
    'Maria Lorena Macyszyn': 'La Libertad Avanza',
    'Maria Lorena Villaverde': 'La Libertad Avanza',
    'Maria Mercedes Llano': 'La Libertad Avanza',
    'Mario Gerardo Huesen': 'La Libertad Avanza',
    'Martin Alexis Menem': 'La Libertad Avanza',
    'Nadia Judith Marquez': 'La Libertad Avanza',
    'Nicolas Fernando Mayoraz': 'La Libertad Avanza',
    'Nicolas Mario Emma': 'La Libertad Avanza',
    'Pablo Miguel Ansaloni': 'La Libertad Avanza',
    'Rocio Belen Bonacci': 'La Libertad Avanza',
    'Romina Diez': 'La Libertad Avanza',
    'Santiago Javier Santurio Rodriguez': 'La Libertad Avanza',
    'Eduardo Gabriel Falcone': 'La Libertad Avanza',
    'Maria Cecilia Ibañez': 'La Libertad Avanza',
    'Oscar Roberto Zago': 'La Libertad Avanza',
    'Maria De Los Angeles Moreno': 'Juntos Por El Cambio',
    'Nancy Viviana Picon Martinez': 'Juntos Por El Cambio',
    'Juan Manuel Lopez': 'Juntos Por El Cambio',
    'Maria Marcela Campagnoli': 'Juntos Por El Cambio',
    'Maria Victoria Borrego': 'Juntos Por El Cambio',
    'Maximiliano Carlos Francisco Ferraro': 'Juntos Por El Cambio',
    'Monica Edith Frade': 'Juntos Por El Cambio',
    'Paula Mariana Oliveto Lago': 'Juntos Por El Cambio',
    'Paula Omodeo': 'Juntos Por El Cambio',
    'Carla Carrizo': 'Juntos Por El Cambio',
    'Danya Tavela': 'Juntos Por El Cambio',
    'Facundo Manes': 'Juntos Por El Cambio',
    'Fernando Carbajal': 'Juntos Por El Cambio',
    'Jorge Colo Rizzotti': 'Juntos Por El Cambio',
    'Juan Carlos Polini': 'Juntos Por El Cambio',
    'Manuel "Colo" Aguirre': 'Juntos Por El Cambio',
    'Marcela Antola': 'Juntos Por El Cambio',
    'Marcela Coli': 'Juntos Por El Cambio',
    'Mariela Giselle Coletta': 'Juntos Por El Cambio',
    'Melina C. Giorgi': 'Juntos Por El Cambio',
    'Pablo Adrian Juliano': 'Juntos Por El Cambio',
    'Alejandra Torres': 'Hacemos Por Nuestro Pais',
    'Carlos Mario Gutierrez': 'Hacemos Por Nuestro Pais',
    'Emilio Monzó': 'Juntos Por El Cambio',
    'Esteban Paulon': 'Hacemos Por Nuestro Pais',
    'Florencio Randazzo': 'Hacemos Por Nuestro Pais',
    'Francisco Alejandro Morchio': 'Juntos Por El Cambio',
    'Ignacio José Garcia Aresca': 'Hacemos Por Nuestro Pais',
    'Jorge Antonio Avila': 'Juntos Por El Cambio',
    'Juan Fernando Brügge': 'Hacemos Por Nuestro Pais',
    'Margarita Rosa Stolbizer': 'Juntos Por El Cambio',
    'Miguel Angel Pichetto': 'Juntos Por El Cambio',
    'Monica Fein': 'Frente Amplio Progresista',
    'Natalia De La Sota': 'Hacemos Por Nuestro Pais',
    'Nicolás María Massot': 'Juntos Por El Cambio',
    'Oscar Agost Carreño': 'Juntos Por El Cambio',
    'Ricardo Hipolito Lopez Murphy': 'Juntos Por El Cambio',
    'Alejandro Bongiovanni': 'Juntos Por El Cambio',
    'Alejandro Oscar Finocchiaro': 'Juntos Por El Cambio',
    'Alvaro Gustavo Gonzalez': 'Juntos Por El Cambio',
    'Ana Clara Romero': 'Juntos Por El Cambio',
    'Anibal Tortoriello': 'Juntos Por El Cambio',
    'Cristian Adrian Ritondo': 'Juntos Por El Cambio',
    'Daiana Fernandez Molero': 'Juntos Por El Cambio',
    'Damian Eduardo Arabia': 'Juntos Por El Cambio',
    'Diego Cesar Santilli': 'Juntos Por El Cambio',
    'Fernando Adolfo Iglesias': 'Juntos Por El Cambio',
    'Gabriel Chumpitaz': 'Juntos Por El Cambio',
    'Gabriela Gisel Besana': 'Juntos Por El Cambio',
    'Gerardo Fabian Milman': 'Juntos Por El Cambio',
    'Germana Maria Figueroa Casas': 'Juntos Por El Cambio',
    'Hector "La Coneja" Baldassi': 'Juntos Por El Cambio',
    'Hernan Santiago Lombardi': 'Juntos Por El Cambio',
    'Javier Sanchez Wrba': 'Juntos Por El Cambio',
    'Jose Negro Nuñez': 'Juntos Por El Cambio',
    'Karina Bachey': 'Juntos Por El Cambio',
    'Laura Rodriguez Machado': 'Juntos Por El Cambio',
    'Luciano Laspina': 'Juntos Por El Cambio',
    'Maria Angel Sotolano': 'Juntos Por El Cambio',
    'Maria Belen Avico': 'Juntos Por El Cambio',
    'Maria Eugenia Vidal': 'Juntos Por El Cambio',
    'Maria Florencia De Sensi': 'Juntos Por El Cambio',
    'Marilu Quiroz': 'Juntos Por El Cambio',
    'Martin Ivan Yeza': 'Juntos Por El Cambio',
    'Martin Maquieyra': 'Juntos Por El Cambio',
    'Martin Miguel Ardohain': 'Juntos Por El Cambio',
    'Nancy Mariana Ballejos': 'Juntos Por El Cambio',
    'Patricia Maria Vasquez': 'Juntos Por El Cambio',
    'R. Emmanuel Bianchetti': 'Juntos Por El Cambio',
    'Sabrina Carlota Ajmechet': 'Juntos Por El Cambio',
    'Sergio Capozzi': 'Juntos Por El Cambio',
    'Silvana Myriam Giudici': 'Juntos Por El Cambio',
    'Silvia Gabriela Lospennato': 'Juntos Por El Cambio',
    'Sofia Brambilla': 'Juntos Por El Cambio',
    'Tito Stefani': 'Juntos Por El Cambio',
    'Veronica Gabriela Razzini': 'Juntos Por El Cambio',
    'Mario Domingo Barletta': 'Juntos Por El Cambio',
    'Alfredo Oscar Vallejos': 'Juntos Por El Cambio',
    'Atilio Francisco Salvador Benedetti': 'Juntos Por El Cambio',
    'Fabio Jose Quetglas': 'Juntos Por El Cambio',
    'Francisco Manuel Monti': 'Juntos Por El Cambio',
    'Gabriela Brouwer De Koning': 'Juntos Por El Cambio',
    'Gerardo Cipolini': 'Juntos Por El Cambio',
    'Jose Federico Tournier': 'Juntos Por El Cambio',
    'Julio Cobos': 'Juntos Por El Cambio',
    'Karina Veronica Banfi': 'Juntos Por El Cambio',
    'Lisandro Nieri': 'Juntos Por El Cambio',
    'Luis Albino Picat': 'Juntos Por El Cambio',
    'Mariano Campero': 'Juntos Por El Cambio',
    'Mario Pablo Cervi': 'Juntos Por El Cambio',
    'Martin A. Arjol': 'Juntos Por El Cambio',
    'Martin Alberto Tetaz': 'Juntos Por El Cambio',
    'Natalia Silvina Sarapura': 'Juntos Por El Cambio',
    'Pamela Verasay': 'Juntos Por El Cambio',
    'Pedro Galimberti': 'Juntos Por El Cambio',
    'Roberto Antonio Sanchez': 'Juntos Por El Cambio',
    'Rodrigo De Loredo': 'Juntos Por El Cambio',
    'Roxana Reyes': 'Juntos Por El Cambio',
    'Soledad Carrizo': 'Juntos Por El Cambio'
};
