export const PROVINCES_BY_LEGISLATORS: Record<string, string> = {
    'Ricardo Garramuño': 'Tierra Del Fuego',
    'Roberto Mario Mirabella': 'Santa Fe',
    '"Colo" Vancsik Daniel A.': 'Misiones',
    'Agustin Domingo': 'Rio Negro',
    'Arrua Pedro Alberto': 'Misiones',
    'Carlos Alberto Fernandez': 'Misiones',
    'Pablo Ismael Outes': 'Salta',
    'Pamela Calletti': 'Salta',
    'Ruiz Yamila Lisette': 'Misiones',
    'Yolanda Graciela Vega': 'Salta',
    'Osvaldo Llancafilo': 'Neuquén',
    'Carlos Facundo Prades': 'Santa Cruz',
    'Jose Luis Garrido': 'Santa Cruz',
    'Sergio Edgardo Acevedo': 'Santa Cruz',
    'Myriam Teresa Bregman': 'Ciudad Autónoma De Buenos Aires',
    'Romina Del Pla': 'Buenos Aires',
    'Monica Leticia Schlotthauer': 'Buenos Aires',
    'Juan Carlos Giordano': 'Buenos Aires',
    'Mercedes Fernandez': 'Ciudad Autónoma De Buenos Aires',
    'Vilma Ripoll': 'Buenos Aires',
    'Vanina Natalia Biasi': 'Ciudad Autónoma De Buenos Aires',
    'Alejandro Ariel Vilca': 'Jujuy',
    'Christian Carlos Hernan Castillo': 'Buenos Aires',
    'Nicolas Del Caño': 'Buenos Aires',
    'Adolfo Bermejo': 'Mendoza',
    'Agustina Lucrecia Propato': 'Buenos Aires',
    'Aldo Adolfo Leiva': 'Chaco',
    'Ana Carolina Gaillard': 'Entre Ríos',
    'Ana Fabiola Aubone': 'San Juan',
    'Ana Maria Ianni': 'Santa Cruz',
    'Andrea Graciela Freites': 'Tierra Del Fuego',
    'Ariel Rauschenberger': 'La Pampa',
    'Bernardo Jose "Pepe" Herrera': 'Santiago Del Estero',
    'Blanca Ines Osuna': 'Entre Ríos',
    'Brenda Magali Vargas Matyi': 'Buenos Aires',
    'Carlos Cisneros': 'Tucumán',
    'Carlos Salomon Heller': 'Ciudad Autónoma De Buenos Aires',
    'Carolina Yutrovic': 'Tierra Del Fuego',
    'Castagneto, Carlos': 'Buenos Aires',
    'Celia Maria Campitelli': 'Santiago Del Estero',
    'Christian Alejandro Zulli': 'Corrientes',
    'Constanza Maria Alonso': 'Buenos Aires',
    'Daniel Fernando Arroyo': 'Buenos Aires',
    'Daniel Gustavo Gollan': 'Buenos Aires',
    'Dante Edgardo Lopez Rodriguez': 'Catamarca',
    'David Sebastian Noblega': 'Catamarca',
    'Diego Giuliano': 'Santa Fe',
    'Eduardo Felix Valdes': 'Ciudad Autónoma De Buenos Aires',
    'Eduardo Leandro Toniolli': 'Santa Fe',
    'Emiliano Estrada': 'Salta',
    'Ernesto Nader Ali': 'San Luis',
    'Estela Mary Del Rosario Neder': 'Santiago Del Estero',
    'Gabriela Beatriz Estevez': 'Córdoba',
    'Gabriela Pedrali': 'La Rioja',
    'German Pedro Martinez': 'Santa Fe',
    'Guillermo Snopek': 'Jujuy',
    'Gustavo Carlos Miguel Gonzalez': 'Santa Cruz',
    'Gustavo Eduardo Bordet': 'Entre Ríos',
    'Gustavo Ramiro Fernandez Patri': 'Formosa',
    'Gutierrez, Carlos Ramiro': 'Buenos Aires',
    'Hilda Clelia Aguirre': 'La Rioja',
    'Hugo Ruben Yasky': 'Buenos Aires',
    'Itai Hagman': 'Ciudad Autónoma De Buenos Aires',
    'Jorge Antonio Romero': 'Corrientes',
    'Jorge Eduardo Chica Muñoz': 'San Juan',
    'Jorge Neri Araujo Hernandez': 'Tierra Del Fuego',
    'Jorge Ricardo Herrera': 'La Rioja',
    'Jose Edgardo Gomez': 'Santiago Del Estero',
    'José Alejandro Glinski': 'Chubut',
    'Juan Manuel Pedrini': 'Chaco',
    'Julia Strada Rodriguez': 'Buenos Aires',
    'Julio Cesar Pereyra': 'Buenos Aires',
    'Kirchner, Maximo': 'Buenos Aires',
    'Leandro Jorge Santoro': 'Ciudad Autónoma De Buenos Aires',
    'Leila Susana Chaher': 'Jujuy',
    'Leopoldo Raul Guido Moreau': 'Buenos Aires',
    'Lili Paponet': 'Mendoza',
    'Lorena Iris Pokoik Garcia': 'Ciudad Autónoma De Buenos Aires',
    'Luciana Potenza': 'Buenos Aires',
    'Luis Eugenio Basterra': 'Formosa',
    'Magali Mastaler': 'Santa Fe',
    'Marcela Fabiana Passo': 'Buenos Aires',
    'Maria Eugenia Alianiello': 'Chubut',
    'Maria Fernanda Avila': 'Catamarca',
    'Maria Florencia Carignano': 'Santa Fe',
    'Maria Gisela Marziotta': 'Ciudad Autónoma De Buenos Aires',
    'Maria Graciela Parola': 'Formosa',
    'Maria Luisa Chomiak': 'Chaco',
    'Maria Luisa Montoto De Rogel': 'Santiago Del Estero',
    'Maria Natalia Zabala Chacur': 'San Luis',
    'Marino, Juan': 'Buenos Aires',
    'Mario Roberto Manrique': 'Buenos Aires',
    'Martin Aveiro': 'Mendoza',
    'Martin Ignacio Soria': 'Rio Negro',
    'Matias Molle': 'Buenos Aires',
    'Micaela Moran': 'Buenos Aires',
    'Monica Edith Litza': 'Buenos Aires',
    'Monica Fernanda Macha': 'Buenos Aires',
    'Moreau, Cecilia': 'Buenos Aires',
    'Nancy Sand': 'Corrientes',
    'Nilda Moyano': 'Santiago Del Estero',
    'Pablo Carro': 'Córdoba',
    'Pablo Todero': 'Neuquén',
    'Pablo Yedlin': 'Tucumán',
    'Paula Andrea Penacca': 'Ciudad Autónoma De Buenos Aires',
    'Ricardo Daniel Daives': 'Santiago Del Estero',
    'Rogelio Iparraguirre': 'Buenos Aires',
    'Roxana Elizabeth Monzon': 'Buenos Aires',
    'Sabrina Selva': 'Buenos Aires',
    'Santiago A. Cafiero': 'Buenos Aires',
    'Sergio Guillermo Casas': 'La Rioja',
    'Sergio Omar Palazzo': 'Buenos Aires',
    'Silvana Micaela Ginocchio': 'Catamarca',
    'Tailhade, Rodolfo': 'Buenos Aires',
    'Tanya Bertoldi': 'Neuquén',
    'Tomas Ledesma': 'Entre Ríos',
    'Vanesa Raquel Siley': 'Buenos Aires',
    'Varinia Lichi Marin': 'La Pampa',
    'Victoria Tolosa Paz': 'Buenos Aires',
    'Volnovich, Luana': 'Buenos Aires',
    'Walberto E. Allende': 'San Juan',
    'Zaracho, Natalia': 'Buenos Aires',
    'Lourdes Micaela Arrieta': 'Mendoza',
    'Agustin Fernandez': 'Tucumán',
    'Elia Mansilla': 'Tucumán',
    'Gladys Medina': 'Tucumán',
    'Alberto Gustavo Arancibia Rodriguez': 'San Luis',
    'Alberto “Bertie” Tiburcio Benegas Lynch': 'Buenos Aires',
    'Alida Monica Ferreyra': 'Ciudad Autónoma De Buenos Aires',
    'Alvaro Martinez': 'Mendoza',
    'Beltran Benedit': 'Entre Ríos',
    'Carla Juliana Santillan Juarez Brahim': 'Buenos Aires',
    'Carlos Alberto Gonzalez D Alessandro': 'San Luis',
    'Carlos Daniel Garcia': 'Chaco',
    'Carlos Raúl Zapata': 'Salta',
    'Carolina Rosana Piparo': 'Buenos Aires',
    'Cesar Hernan Treffinger': 'Chubut',
    'Claudio Lisandro Almiron': 'Corrientes',
    'Facundo Correa Llano': 'Mendoza',
    'Florencia Klipauka Lewtak': 'Misiones',
    'Gabriel Marcos Bornoroni': 'Córdoba',
    'Gerardo Gustavo Gonzalez': 'Formosa',
    'Guillermo Tristan Montenegro': 'Buenos Aires',
    'Jorge Santiago Pauli': 'Tierra Del Fuego',
    'Jose Asad Peluc': 'San Juan',
    'José Luis Espert': 'Buenos Aires',
    'Julio Aurelio Moreno': 'Salta',
    'Lilia Adela Bolukalo Lemoine': 'Buenos Aires',
    'Manuel Quintar': 'Jujuy',
    'Marcela Marina Pagano': 'Buenos Aires',
    'Maria Celeste Ponce': 'Córdoba',
    'Maria Emilia Orozco': 'Salta',
    'Maria Fernanda Araujo': 'Ciudad Autónoma De Buenos Aires',
    'Maria Lorena Macyszyn': 'Buenos Aires',
    'Maria Lorena Villaverde': 'Rio Negro',
    'Maria Mercedes Llano': 'Mendoza',
    'Mario Gerardo Huesen': 'Tucumán',
    'Martin Alexis Menem': 'La Rioja',
    'Nadia Judith Marquez': 'Neuquén',
    'Nicolas Fernando Mayoraz': 'Santa Fe',
    'Nicolas Mario Emma': 'Ciudad Autónoma De Buenos Aires',
    'Pablo Miguel Ansaloni': 'Buenos Aires',
    'Rocio Belen Bonacci': 'Santa Fe',
    'Romina Diez': 'Santa Fe',
    'Santiago Javier Santurio Rodriguez': 'Buenos Aires',
    'Eduardo Gabriel Falcone': 'Buenos Aires',
    'Maria Cecilia Ibañez': 'Córdoba',
    'Oscar Roberto Zago': 'Ciudad Autónoma De Buenos Aires',
    'Maria De Los Angeles Moreno': 'San Juan',
    'Nancy Viviana Picon Martinez': 'San Juan',
    'Juan Manuel Lopez': 'Buenos Aires',
    'Maria Marcela Campagnoli': 'Buenos Aires',
    'Maria Victoria Borrego': 'Buenos Aires',
    'Maximiliano Carlos Francisco Ferraro': 'Ciudad Autónoma De Buenos Aires',
    'Monica Edith Frade': 'Buenos Aires',
    'Paula Mariana Oliveto Lago': 'Ciudad Autónoma De Buenos Aires',
    'Paula Omodeo': 'Tucumán',
    'Carla Carrizo': 'Ciudad Autónoma De Buenos Aires',
    'Danya Tavela': 'Buenos Aires',
    'Facundo Manes': 'Buenos Aires',
    'Fernando Carbajal': 'Formosa',
    'Jorge Colo Rizzotti': 'Jujuy',
    'Juan Carlos Polini': 'Chaco',
    'Manuel "Colo" Aguirre': 'Corrientes',
    'Marcela Antola': 'Entre Ríos',
    'Marcela Coli': 'La Pampa',
    'Mariela Giselle Coletta': 'Ciudad Autónoma De Buenos Aires',
    'Melina C. Giorgi': 'Santa Fe',
    'Pablo Adrian Juliano': 'Buenos Aires',
    'Alejandra Torres': 'Córdoba',
    'Carlos Mario Gutierrez': 'Córdoba',
    'Emilio Monzó': 'Buenos Aires',
    'Esteban Paulon': 'Santa Fe',
    'Florencio Randazzo': 'Buenos Aires',
    'Francisco Alejandro Morchio': 'Entre Ríos',
    'Ignacio José Garcia Aresca': 'Córdoba',
    'Jorge Antonio Avila': 'Chubut',
    'Juan Fernando Brügge': 'Córdoba',
    'Margarita Rosa Stolbizer': 'Buenos Aires',
    'Miguel Angel Pichetto': 'Buenos Aires',
    'Monica Fein': 'Santa Fe',
    'Natalia De La Sota': 'Córdoba',
    'Nicolás María Massot': 'Buenos Aires',
    'Oscar Agost Carreño': 'Córdoba',
    'Ricardo Hipolito Lopez Murphy': 'Ciudad Autónoma De Buenos Aires',
    'Alejandro Bongiovanni': 'Santa Fe',
    'Alejandro Oscar Finocchiaro': 'Buenos Aires',
    'Alvaro Gustavo Gonzalez': 'Ciudad Autónoma De Buenos Aires',
    'Ana Clara Romero': 'Chubut',
    'Anibal Tortoriello': 'Rio Negro',
    'Cristian Adrian Ritondo': 'Buenos Aires',
    'Daiana Fernandez Molero': 'Ciudad Autónoma De Buenos Aires',
    'Damian Eduardo Arabia': 'Ciudad Autónoma De Buenos Aires',
    'Diego Cesar Santilli': 'Buenos Aires',
    'Fernando Adolfo Iglesias': 'Ciudad Autónoma De Buenos Aires',
    'Gabriel Chumpitaz': 'Santa Fe',
    'Gabriela Gisel Besana': 'Buenos Aires',
    'Gerardo Fabian Milman': 'Buenos Aires',
    'Germana Maria Figueroa Casas': 'Santa Fe',
    'Hector "La Coneja" Baldassi': 'Córdoba',
    'Hernan Santiago Lombardi': 'Buenos Aires',
    'Javier Sanchez Wrba': 'Buenos Aires',
    'Jose Negro Nuñez': 'Santa Fe',
    'Karina Bachey': 'San Luis',
    'Laura Rodriguez Machado': 'Córdoba',
    'Luciano Laspina': 'Santa Fe',
    'Maria Angel Sotolano': 'Buenos Aires',
    'Maria Belen Avico': 'Córdoba',
    'Maria Eugenia Vidal': 'Ciudad Autónoma De Buenos Aires',
    'Maria Florencia De Sensi': 'Buenos Aires',
    'Marilu Quiroz': 'Chaco',
    'Martin Ivan Yeza': 'Buenos Aires',
    'Martin Maquieyra': 'La Pampa',
    'Martin Miguel Ardohain': 'La Pampa',
    'Nancy Mariana Ballejos': 'Entre Ríos',
    'Patricia Maria Vasquez': 'Buenos Aires',
    'R. Emmanuel Bianchetti': 'Misiones',
    'Sabrina Carlota Ajmechet': 'Ciudad Autónoma De Buenos Aires',
    'Sergio Capozzi': 'Rio Negro',
    'Silvana Myriam Giudici': 'Ciudad Autónoma De Buenos Aires',
    'Silvia Gabriela Lospennato': 'Buenos Aires',
    'Sofia Brambilla': 'Corrientes',
    'Tito Stefani': 'Tierra Del Fuego',
    'Veronica Gabriela Razzini': 'Santa Fe',
    'Mario Domingo Barletta': 'Santa Fe',
    'Alfredo Oscar Vallejos': 'Corrientes',
    'Atilio Francisco Salvador Benedetti': 'Entre Ríos',
    'Fabio Jose Quetglas': 'Buenos Aires',
    'Francisco Manuel Monti': 'Catamarca',
    'Gabriela Brouwer De Koning': 'Córdoba',
    'Gerardo Cipolini': 'Chaco',
    'Jose Federico Tournier': 'Corrientes',
    'Julio Cobos': 'Mendoza',
    'Karina Veronica Banfi': 'Buenos Aires',
    'Lisandro Nieri': 'Mendoza',
    'Luis Albino Picat': 'Córdoba',
    'Mariano Campero': 'Tucumán',
    'Mario Pablo Cervi': 'Neuquén',
    'Martin A. Arjol': 'Misiones',
    'Martin Alberto Tetaz': 'Ciudad Autónoma De Buenos Aires',
    'Natalia Silvina Sarapura': 'Jujuy',
    'Pamela Verasay': 'Mendoza',
    'Pedro Galimberti': 'Entre Ríos',
    'Roberto Antonio Sanchez': 'Tucumán',
    'Rodrigo De Loredo': 'Córdoba',
    'Roxana Reyes': 'Santa Cruz',
    'Soledad Carrizo': 'Córdoba'
};